import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ShantiMantra from "@/components/ShantiMantra";
import UpanishadEmblem from "@/components/UpanishadEmblem";
import { concepts, relatedUpanishads, upanishadBySlug, upanishads } from "@/data/content";

export function generateStaticParams() { return upanishads.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = upanishadBySlug(slug); return { title: item ? `${item.name} Upanishad` : "Teaching not found", description: item?.summary }; }
export default async function UpanishadPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = upanishadBySlug(slug); if (!item) notFound(); const index = upanishads.indexOf(item); const related = relatedUpanishads(item); return <main id="main-content">
  <header className="upanishad-hero" style={{ "--accent": item.color } as React.CSSProperties}><div className="hero-orbit">{item.emblem ? <div className="hero-emblem-lockup"><UpanishadEmblem emblem={item.emblem} variant="hero" labelled /><span className="hero-emblem-script" aria-hidden="true">{item.devanagari}</span></div> : <span className="hero-devanagari" aria-hidden="true">{item.devanagari}</span>}</div><div className="hero-copy"><Link className="back-link" href="/explore">← The ten teachings</Link><p className="eyebrow">{String(index + 1).padStart(2, "0")} · {item.meaning}</p><h1>{item.name}<br /><em>Upanishad</em></h1><p className="hero-question">{item.question}</p></div></header>
  <div className="profile-layout content-width"><article className="profile-main"><section><p className="eyebrow">In brief</p><p className="lead-copy">{item.summary}</p><p>{item.whyItMatters}</p></section><section className="passage"><span aria-hidden="true">“</span><blockquote>{item.passage.text}</blockquote><p>{item.passage.locator}</p><small>Placeholder wording—not a published translation</small></section><ShantiMantra slug={item.slug} /></article><aside className="profile-aside"><section><p className="eyebrow">Key themes</p><div className="theme-stack">{item.themes.map((t, i) => <div key={t}><span>0{i + 1}</span>{t}</div>)}</div></section><section><p className="eyebrow">Ideas in this teaching</p><ul className="concept-list">{item.conceptIds.map((id) => { const c = concepts.find((concept) => concept.slug === id)!; return <li key={id}><Link href={`/concepts/${id}`}><span style={{ background: c.color }} />{c.name}<b>→</b></Link></li>; })}</ul></section></aside></div>
  <section className="related-section"><div className="content-width"><div className="section-heading"><div><p className="eyebrow">Continue exploring</p><h2>Nearby in the<br />constellation.</h2></div></div><div className="related-list">{related.map((u) => <Link href={`/upanishads/${u.slug}`} key={u.slug}><span className={`related-mark ${u.emblem ? "has-emblem" : ""}`} style={{ "--emblem-color": u.color } as React.CSSProperties}><UpanishadEmblem emblem={u.emblem} variant="related" /><span className="devanagari">{u.devanagari}</span></span><div><p className="eyebrow">{u.meaning}</p><h3>{u.name}</h3></div><span>↗</span></Link>)}</div></div></section>
  <nav className="profile-pagination" aria-label="Other Upanishads"><Link href={`/upanishads/${upanishads[(index - 1 + upanishads.length) % upanishads.length].slug}`}>← Previous teaching</Link><span>{index + 1} / {upanishads.length}</span><Link href={`/upanishads/${upanishads[(index + 1) % upanishads.length].slug}`}>Next teaching →</Link></nav>
  </main>; }
